### ISSUE TITLE
Suricata does not send data to 3 Mikrotik

### ISSUE THREAD

**Issue by STARWORKBY** [angolo40/mikrocata2selks#17]
Hi! Help me figure it out, Suricata does not send data to 3 Mikrotik. 

I did everything according to the instructions. I use Debian 12.5. 

The packets arrive on 3 virtual interfaces: tzsp0, tzsp1, tzsp2. 

I stopped 3 services: mikrocataTZSP0.service, mikrocataTZSP1.service, mikrocataTZSP2.service. 

I started it:python3 /usr/local/bin/mikrocataTZSP0.py
![1](https://github.com/user-attachments/assets/0fe23643-7a85-4673-9bcc-f34bc95082b6)

python3 /usr/local/bin/mikrocataTZSP1.py
![2](https://github.com/user-attachments/assets/8954beb0-7092-4417-8689-239451fad8e4)

python3 /usr/local/bin/mikrocataTZSP2.py
![3](https://github.com/user-attachments/assets/a15ebd49-4e63-4b23-96bc-0a7b0b0f3bd1)

![4](https://github.com/user-attachments/assets/804f9bb3-4fe2-403c-b211-6c6ba3ebf5e7)
![5](https://github.com/user-attachments/assets/5431f610-ab10-41a9-a3eb-1065cf39ece8)

![6](https://github.com/user-attachments/assets/1fbff307-c884-4be4-963d-5156f603fcb7)

**Comment by angolo40** [comment]
Hello, can u please share me your WHITELIST_IPS string in mikrocataTZSPx.py

**Comment by STARWORKBY** [comment]
WHITELIST_IPS = (WAN_IP, LOCAL_IP_PREFIX, "1.1.1.10", "1.1.1.90", "77.88.8.8", "8.8.4.4")

**Comment by angolo40** [comment]
It seems correct unless WAN_IP or LOCAL_IP_PREFIX contains multiple values.
If that's the case, you should modify the code as follows:
WAN_IP = "..."
LOCAL_IP_PREFIX = "..."
The two variables should contain a single IP address for WAN_IP, and LOCAL_IP_PREFIX should contain a single LAN prefix in the format 192.168.
If you need to add another local IP address to the whitelist, you can include it in WHITELIST_IPS as a prefix like 10.0. for example.

**Comment by STARWORKBY** [comment]
I specified two LOCAL_IP_PREFIX IP addresses = "172.16.", "192.168.". I removed "192.168." and everything worked.
Thank you very much!

**Comment by angolo40** [comment]
Happy to know that.
Please give a Star to the project :smile:
