### ISSUE TITLE
Rule severity filter

### ISSUE THREAD

**Issue by paTaNiNho** [angolo40/mikrocata2selks#2]
Hello,
first I would like to thank you for this easy and working solution of your script!

Do you think that will be possible to modified your code for filtering each alert output based on `severity`?

For example I would like to send to the MikroTik Firewall only IPs with `severity:1` (red ones). And ignore the other two rules.
![image](https://user-images.githubusercontent.com/58893045/222183569-8f6d709a-6390-4d43-a9ac-e1642a729ac4.png)

Thank you for your time and answer... 💯 
Regards...

**Comment by angolo40** [comment]
Hello, 
this is not an issue but a request.
Anyway i added the function in mikrocata.py
Replace the old file /usr/local/bin/mikrocata.py with the new one, edit mikrotik information inside and then reload the service whith "systemctl restart mikrocata.service"
