### ISSUE TITLE
Question about syntax in .PY Config

### ISSUE THREAD

**Issue by sandrob1992** [angolo40/mikrocata2selks#23]
Hello to Community and thanks for such a good application

I have managed to run the app and integrate it with my Mikrotik and i am very happy about it :) but i got a question about .py config file

I have two WAN ports and appropriate WAN ip addresses (STATIC) ...which traffic i want to send to SELKS, but i don't know exactly if i have written down those Public IP addresses in .py config whitelist in a good manner.
========================================================================================
# You can add your WAN IP, so it doesn't get mistakenly blocked (don't leave empty string)
WAN_IP = "x.x.x.x", "x.x.x.x"

So is this syntax good? or does it need any change? also I'm interested if I add in "WAN IPS" in above line what i have mentioned...should i add those WAN IPS in "WHITELIST_IPS" line additionally? 

WHITELIST_IPS = (WAN_IP, LOCAL_IP_PREFIX, "127.0.0.1", "1.1.1.1", "8.8.8.8", "192.168.0.0/16", "x.x.x.x", "x.x.x.x", fe80:")

Also about "LOCAL_IP_PREFIX = "192.168."   as I guess i can add a local subnet here which i am using in local area network...for instance 192.168.0.0/16.....but should i add that subnet in "WHITELIST_IPS" additionally? 

i would appreciate for your suggestions

thanks

**Comment by angolo40** [comment]
Hello,

if u want to put two WAN IPs u need to use this sintax:
WAN_IP = "x.x.x.x", "x.x.x.x"

also u have to modify from
WHITELIST_IPS = (WAN_IP, LOCAL_IP_PREFIX, "127.0.0.1", "1.1.1.1", "8.8.8.8", "192.168.0.0/16", "x.x.x.x", "x.x.x.x", fe80:")

to (note the '+' operator)
WHITELIST_IPS = WAN_IP + (LOCAL_IP_PREFIX, "127.0.0.1", "1.1.1.1", "8.8.8.8", "192.168.0.0/16", "x.x.x.x", "x.x.x.x", fe80:")

This will create a clean list of all your IPs:
("x.x.x.x", "x.x.x.x", "192.168.", "127.0.0.1", "1.1.1.1", "8.8.8.8", "fe80:")

Do NOT add your WAN IPs twice by listing them again in WHITELIST_IPS, as they're already included via the WAN_IP concatenation.
Avoid this:
WHITELIST_IPS = (WAN_IP, LOCAL_IP_PREFIX, "127.0.0.1", "1.1.1.1", "8.8.8.8", "x.x.x.x", "x.x.x.x", "fe80:")

 Regarding LOCAL_IP_PREFIX and local subnet:
 yes, you have to enter your local subnet but no need to add it twice in WHITELIST_IPS as it's already included via LOCAL_IP_PREFIX
