### ISSUE TITLE
Compatibility with Ubuntu 20.04

### ISSUE THREAD

**Issue by LaSepp** [angolo40/mikrocata2selks#5]
The easyinstall.sh script will work on Ubuntu 20.04, but the command for docker compose is "docker compose up -d" instead of "docker-compose up -d".

Maybe add a flavour detection to the script?

**Comment by angolo40** [comment]
Definitivly i will add a command detection.
Thanks for the suggestion

**Comment by angolo40** [comment]
changed docker compose command for docker v2 compatibility.
